# Generated by Django 4.0.5 on 2022-09-18 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_limit', models.FloatField()),
                ('highest_limit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Deposit_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw_Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_limit', models.FloatField(blank=True, null=True)),
                ('highest_limit', models.FloatField(blank=True, null=True)),
                ('club_lowest_limit', models.FloatField(blank=True, null=True)),
                ('club_highest_limit', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=30)),
                ('send_to', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Withdraw_Account_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=20, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.withdraw_method')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('send_to', models.CharField(max_length=20)),
                ('send_from', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('transaction_number', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('cancel', 'Cancel'), ('return', 'Return')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Deposit_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.deposit_method')),
            ],
        ),
    ]
