# Generated by Django 4.0.5 on 2022-09-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirm'), ('Cancelled', 'Cancel'), ('Returned', 'Return')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirm'), ('Cancelled', 'Cancel')], default='pending', max_length=50),
        ),
    ]
