# Generated by Django 4.0.5 on 2022-09-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_betquestion_finish_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AddField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
