# Generated by Django 4.0.5 on 2022-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_match_date_remove_match_time_match_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='betquestion',
            name='finished_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betquestion',
            name='identifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finish', 'Finish'), ('cancel', 'Cancel'), ('return', 'Return')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='betquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
