# Generated by Django 4.0.5 on 2022-09-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_bet', '0002_alter_placebet_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placebet',
            options={'ordering': ['-date', '-time']},
        ),
    ]
