# Generated by Django 4.0.5 on 2022-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_bet', '0003_alter_placebet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placebet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='placebet',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
