# Generated by Django 4.0.5 on 2022-09-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_bet', '0004_alter_placebet_date_alter_placebet_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebet',
            name='club_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
