# Generated by Django 4.0.5 on 2022-09-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_bet', '0005_placebet_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebet',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
