# Generated by Django 4.0.5 on 2022-09-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_bet', '0006_placebet_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placebet',
            options={'ordering': ['-date_time']},
        ),
        migrations.RemoveField(
            model_name='placebet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='placebet',
            name='time',
        ),
        migrations.AddField(
            model_name='placebet',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
