# Generated by Django 4.0.5 on 2022-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_bet', '0008_remove_placebet_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebet',
            name='question_identifier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
